<?php

/**
 * Implements hook_islandora_breadcrumbs_alter().
 *
 * Removes Islandora top-level breadcrumbs that would send the user astray.
 */
function islandora_breadcrumb_fix_islandora_breadcrumbs_alter(&$breadcrumbs, $item) {
  foreach ($breadcrumbs as $value) {
    if (strpos($value, ':root">') !== FALSE) {  ## Member's root level collections
      $breadcrumbs = array_diff($breadcrumbs, array($value));
    }
    if (strpos($value, 'islandora">') !== FALSE) {  ## Top level Islandora collection
      $breadcrumbs = array_diff($breadcrumbs, array($value));
    }
  }
}

/**
 * Implements hook_menu_breadcrumb_alter().
 * 
 * This removes certain unwanted breadcrumbs. The islandora breadcrumb alter hook
 * is limited to views and solr results pages, so this should catch the rest.
 */
function islandora_breadcrumb_fix_menu_breadcrumb_alter(&$active_trail, $item){
  foreach ($active_trail as $key => $value){
    if (strpos($value['link_path'], ':root') !== FALSE) {  ## Member's root level collections
      unset($active_trail[$key]);
    }
    if (strpos($value['link_path'], 'islandora') !== FALSE) {  ## Top level Islandora collection
      unset($active_trail[$key]);
    }
  }
}

/**
 * Implements hook_menu().
 *
 * Prevent user from getting access to islandora:root
 */
function islandora_breadcrumb_fix_menu() {
	$items['islandora/object/islandora:root'] = array (
		'page callback' => 'islandora_breadcrumb_intercept_root',
	);
	return $items;
}
